"""新增 17 项国家级非遗，补齐缺失的 17 个省级行政区，使非遗地图全国铺满。

运行：python3 scripts/append_items2.py  （幂等：已有同 id 则跳过）
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "structured" / "heritage_items.json"

NEW = [
    {
        "id": "h_hezhe",
        "name": "赫哲族鱼皮制作技艺",
        "category": "传统技艺 · 服饰",
        "region": "黑龙江省佳木斯市",
        "era": "明代文献已有记载，传承逾千年",
        "level": "国家级非物质文化遗产",
        "description": "赫哲族是中国人口最少的民族之一，世居黑龙江、乌苏里江畔，历史上以鱼皮为衣，素有“鱼皮部落”之称。制作时取大马哈鱼等淡水鱼，经剥皮、去鳞、熟制、阴干、拼接缝制而成。鱼皮衣物轻便防水、抗风耐寒，纹样多取鱼尾、浪花、鹿角等自然形态。",
        "cultural_meaning": "鱼皮技艺是渔猎文明的活化石，体现赫哲族“取之于江、用之于江”的生存智慧与天人合一的生态观，也是北方渔猎民族服饰史的重要物证。",
        "craft_process": "选鱼 → 剥皮 → 去鳞刮脂 → 熟皮（木槌反复捶打使纤维柔软）→ 晾干压平 → 裁剪 → 鱼皮线缝制 → 点缀染色鱼皮剪贴纹样。",
        "representative_works": ["鱼皮袍“卡克塔斯”", "鱼皮画《赫哲神韵》", "鱼皮剪纸纹样"],
        "representative_inheritors": ["尤忠德（国家级代表性传承人）", "付明（鱼皮技艺传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_nonglewu",
        "name": "朝鲜族农乐舞",
        "category": "传统舞蹈 · 民俗舞蹈",
        "region": "吉林省延边朝鲜族自治州",
        "era": "源于古代农耕祭祀，传承上千年",
        "level": "国家级非物质文化遗产",
        "description": "农乐舞是朝鲜族最具代表性的民间舞蹈，集音乐、舞蹈、杂技于一体，常见于节日庆典与农事祭祀。表演由长鼓领跑，舞者在象帽上系长彩带甩出旋转弧线，配合舞童叠罗汉与队列变换。2009 年列入联合国教科文组织人类非物质文化遗产代表作名录。",
        "cultural_meaning": "农乐舞承载朝鲜族崇尚自然、敬天乐群的集体精神，是社区凝聚与岁时节令的重要仪式，也是中国少数民族舞蹈艺术的高峰之一。",
        "craft_process": "乐队起乐（唢呐、长鼓、圆鼓）→ 杂甩队列入场 → 象帽甩彩带（平转、立转、旋回转）→ 舞童叠罗汉 → 舞者即兴竞演 → 全场共舞收束。",
        "representative_works": ["《象帽舞》", "《长鼓舞》", "《江江水月郎》"],
        "representative_inheritors": ["金明春（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_unesco"],
    },
    {
        "id": "h_xiuyan",
        "name": "岫岩玉雕",
        "category": "传统美术 · 雕刻",
        "region": "辽宁省鞍山市岫岩满族自治县",
        "era": "新石器时代已用玉，红山文化玉器即取材于此",
        "level": "国家级非物质文化遗产",
        "description": "岫岩玉是中国四大名玉之一，主产于辽宁岫岩，分蛇纹石质玉与透闪石质玉（析木玉）。岫岩玉雕以花玉巧色著称，讲究量料取材、因色施艺，擅长表现山水、花鸟、仕女与大型玉雕摆件。",
        "cultural_meaning": "岫岩玉雕上承红山文化“唯玉为葬”的礼玉传统，下启东北民间玉俗，是中华玉文化多元一体格局的重要一环。",
        "craft_process": "相玉 → 设计画稿 → 开料 → 粗雕（铡、錾）→ 细雕（勾、撞）→ 打磨 → 抛光 → 上蜡。",
        "representative_works": ["花玉摆件《鹊桥会》", "析木玉《清明上河图》", "岫岩玉大佛"],
        "representative_inheritors": ["李洪才（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_guxiu",
        "name": "顾绣",
        "category": "传统美术 · 刺绣",
        "region": "上海市松江区",
        "era": "明代嘉靖年间由顾名世家族创始",
        "level": "国家级非物质文化遗产",
        "description": "顾绣又称“露香园绣”，起源于明代上海顾名世家族，以韩希孟所绣《洗马图》等“画绣”最负盛名。其特点是以针代笔、以线代墨，追求书画神韵，劈丝细过发色，兼用施针、虚实针表现水墨浓淡，成品几与原画无异。",
        "cultural_meaning": "顾绣开创“画绣”传统，直接影响苏绣、湘绣等流派，是文人审美进入民间工艺的典范，也是上海地区手工艺史的高光。",
        "craft_process": "读画 → 选绢上绷 → 劈丝配色 → 以针代笔施绣（施针、虚实针、滚针）→ 诗书画印配合 → 装裱。",
        "representative_works": ["《洗马图》（韩希孟）", "《花溪渔隐》", "《扁豆蜻蜓》"],
        "representative_inheritors": ["钱月华（国家级代表性传承人）", "朱庆余（顾绣传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_tuiuang",
        "name": "平遥推光漆器",
        "category": "传统技艺 · 漆器",
        "region": "山西省晋中市平遥县",
        "era": "唐代已有记载，明清达到鼎盛",
        "level": "国家级非物质文化遗产",
        "description": "平遥推光漆器以手掌推出光泽、不用机械抛光而得名，与福州脱胎漆器、成都漆器并称中国三大漆器。以木胎为主，经裱布、刮灰、上漆、阴干数十道工序，最后以手掌反复推擦出镜面光泽，再绘金漆彩绘、堆漆雕刻。",
        "cultural_meaning": "推光漆器是晋商文化与北方漆艺交汇的产物，其“手掌推光”的极致耐心，被视为匠人精神的物化表达。",
        "craft_process": "选胎 → 裱布 → 刮灰（三道以上）→ 上漆阴干（反复多遍）→ 打磨 → 手掌推光（蘸麻油、砖灰）→ 描金彩绘 → 嵌玉点翠 → 罩光。",
        "representative_works": ["《晋商大院》屏风", "推光漆器首饰盒", "堆漆《百子图》"],
        "representative_inheritors": ["薛生金（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_zhuxian",
        "name": "朱仙镇木版年画",
        "category": "传统美术 · 民间美术",
        "region": "河南省开封市朱仙镇",
        "era": "北宋兴起，明清鼎盛",
        "level": "国家级非物质文化遗产",
        "description": "朱仙镇木版年画是中国木版年画的源头之一，与天津杨柳青、山东潍坊、苏州桃花坞并称四大年画。以木版分色套印，色版五六至八九不等，用色浑厚浓烈（槐黄、木红、葵绿、铜黑），人物造型夸张，线条粗犷古朴，门神题材最具代表性。",
        "cultural_meaning": "年画是中原民间信仰与节俗的图像载体，门神、灶王等题材寄托驱邪纳福的愿望，也记录了百姓的审美与价值观。",
        "craft_process": "刻版（线版+色版）→ 调色（矿物植物色）→ 套印（先墨线后色版依次叠印）→ 晾晒 → 人工开脸点睛。",
        "representative_works": ["《步下鞭》门神", "《刘海戏金蟾》", "《钟馗》"],
        "representative_inheritors": ["任鹤林（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_hanxiu",
        "name": "汉绣",
        "category": "传统美术 · 刺绣",
        "region": "湖北省武汉市",
        "era": "承战国楚地刺绣传统演变而来",
        "level": "国家级非物质文化遗产",
        "description": "汉绣流行于湖北武汉、沙市、洪湖一带，上承楚绣扁平金线、浓墨重彩的遗风。以齐针为主，讲究“花无正果、热闹为先”，色彩浓艳对比强烈，多用金线盘绣，成品饱满厚重，尤擅绣制戏衣、帐幔与盘金龙凤。",
        "cultural_meaning": "汉绣是楚文化浪漫瑰丽气质的延续，其“满、亮、艳”的风格与荆楚漆器、丝织一脉相承，见证武汉作为九省通衢的商埠繁华。",
        "craft_process": "画稿 → 上绷 → 配色 → 齐针铺底 → 盘金勾边 → 缀珠贴片 → 装裱。",
        "representative_works": ["盘金绣《黄鹤楼》", "戏曲衣箱龙凤袍", "《虎》"],
        "representative_inheritors": ["任本荣（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_xiangxiu",
        "name": "湘绣",
        "category": "传统美术 · 刺绣",
        "region": "湖南省长沙市",
        "era": "源于湖南民间刺绣，清代独立成系",
        "level": "国家级非物质文化遗产",
        "description": "湘绣与苏绣、粤绣、蜀绣并称中国四大名绣，以长沙为中心。首创鬅毛针表现狮虎皮毛的蓬松质感，双面全异绣可在同一底料正反两面绣出不同形象。用色借鉴国画渲染，讲究色线掺针过渡。",
        "cultural_meaning": "湘绣将文人画意与民间技艺结合，《狮虎》等作品近现代屡屡作为国礼，是湖南的文化名片。",
        "craft_process": "画稿 → 上绷 → 劈丝配色 → 鬅毛针/掺针施绣 → 双面异绣（反面藏头）→ 装裱。",
        "representative_works": ["《狮》", "《虎》", "双面全异绣《花木兰》"],
        "representative_inheritors": ["刘爱云（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_dongda",
        "name": "侗族大歌",
        "category": "传统音乐 · 民歌",
        "region": "广西壮族自治区柳州市三江侗族自治县",
        "era": "宋代已有侗人歌会记载",
        "level": "国家级非物质文化遗产",
        "description": "侗族大歌是多声部、无指挥、无伴奏的民间合唱，分声音大歌、叙事大歌、童声大歌等。高低声部自然和声，模拟蝉鸣鸟啭流水之声，一人领唱、众人相和，2009 年列入联合国教科文组织人类非物质文化遗产代表作名录。",
        "cultural_meaning": "大歌是侗族“饭养身、歌养心”生命观的体现，也是没有文字的民族保存历史、传递伦理的口头史书。",
        "craft_process": "鼓楼赛歌堂 → 起歌（领唱定调）→ 分声部叠唱 → 拟声段（蝉鸣、鸟语）→ 叙事长歌 → 送客歌收束。",
        "representative_works": ["《蝉之歌》", "《五月蝉之歌》", "《大山真好》"],
        "representative_inheritors": ["吴家兴（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_unesco"],
    },
    {
        "id": "h_lizu",
        "name": "黎族传统纺染织绣技艺",
        "category": "传统技艺 · 纺织",
        "region": "海南省五指山市",
        "era": "三千年前海南岛已有此类技艺",
        "level": "国家级非物质文化遗产",
        "description": "黎锦是中国最早的棉纺织技艺之一，元代黄道婆曾向黎族学习擀弹纺织之法并传至江南。以踞腰织机（腰机）织造，用植物染料（蓝靛、苏木）染色，绣染结合，几何纹样抽象大胆，2009 年列入联合国教科文组织人类非物质文化遗产代表作名录。",
        "cultural_meaning": "黎锦被誉为“纺织史活化石”，其人形纹、蛙纹记录黎族图腾与祖先崇拜，是无文字民族的“无字史书”。",
        "craft_process": "种棉采棉 → 脱籽弹棉 → 纺线 → 植物染色（浸染晾晒）→ 腰机踞织 → 绣花扎染 → 整理。",
        "representative_works": ["龙被", "黎锦筒裙", "人形纹挂锦"],
        "representative_inheritors": ["符林兰（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_unesco"],
    },
    {
        "id": "h_liangping",
        "name": "梁平木版年画",
        "category": "传统美术 · 民间美术",
        "region": "重庆市梁平区",
        "era": "清康熙年间形成",
        "level": "国家级非物质文化遗产",
        "description": "梁平年画是川东门户的重要年画产地，用二合二灰土纸印制，色版以红、绿、黄为主，人物造型头大身短、憨态可掬，独创印金与粉蜡笺工艺，门神画与洋仙（戏曲故事）题材并重。",
        "cultural_meaning": "梁平年画承载川东移民社会的节俗与审美，是研究巴蜀民间信仰与印刷史的重要实物。",
        "craft_process": "刻版 → 调色（土红、品绿）→ 套印 → 手绘开脸 → 印金装饰 → 晾晒。",
        "representative_works": ["《门神·秦琼敬德》", "《盗仙草》", "《四郎探母》"],
        "representative_inheritors": ["徐家辉（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_laran",
        "name": "苗族蜡染技艺",
        "category": "传统技艺 · 印染",
        "region": "贵州省安顺市",
        "era": "秦汉五溪地区已有蜡染记载",
        "level": "国家级非物质文化遗产",
        "description": "蜡染古称蜡缬，苗族以铜刀蘸蜂蜡在白布上绘图，入蓝靛缸浸染，去蜡后显白花。因蜡液自然龟裂形成独一无二的冰纹。纹样多为涡旋、铜鼓、鸟蝶、鱼龙，被称作“穿在身上的史诗”。",
        "cultural_meaning": "蜡染是苗族记录迁徙与祖先记忆的方式，冰纹的偶然性被视为自然与人共同创作的结果，体现天人共创的造物观。",
        "craft_process": "绘制蜡画（铜刀蘸蜡）→ 浸染（蓝靛反复多次）→ 出缸氧化 → 漂洗去蜡 → 晾晒捶打增亮。",
        "representative_works": ["涡旋纹桌布", "鸟纹背扇", "蜡染长卷《苗族迁徙图》"],
        "representative_inheritors": ["杨金秀（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_tangka",
        "name": "唐卡（勉唐画派）",
        "category": "传统美术 · 绘画",
        "region": "西藏自治区拉萨市",
        "era": "松赞干布时期已现雏形",
        "level": "国家级非物质文化遗产",
        "description": "唐卡是藏族卷轴画，以棉麻为底、矿物颜料绘制，历经构图、白描、上色、开眼、装裱等工序，色彩历久弥新。勉唐画派由 15 世纪钦孜·勉唐大师创立，构图严谨、线条精细，为西藏绘画三大流派之首。",
        "cultural_meaning": "唐卡是“移动的佛堂”，承载藏族的宗教宇宙观与度量经规范，也是高原矿物色彩与工笔技艺的集大成者。",
        "craft_process": "制布（涂胶矾打磨）→ 起稿打线（依度量经比例）→ 白描 → 矿物颜料分层上色 → 开脸点睛 → 金线勾勒 → 卷轴装裱。",
        "representative_works": ["《无量光佛》", "坛城唐卡", "《格萨尔王》"],
        "representative_inheritors": ["丹巴绕旦（勉唐画派传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_huaer",
        "name": "花儿",
        "category": "传统音乐 · 民歌",
        "region": "青海省西宁市",
        "era": "明代即盛行于西北",
        "level": "国家级非物质文化遗产",
        "description": "花儿是流传于青海、甘肃、宁夏、新疆多民族间的山歌，2009 年列入联合国教科文组织人类非物质文化遗产代表作名录。曲令众多（如《河州大令》《互助直令》），即兴对唱，一年开“花儿会”数十场，参会者动辄数万。",
        "cultural_meaning": "花儿是多民族共享的口头传统，歌会成为青年社交与民俗交流的场域，体现中华文化多元一体的生动样态。",
        "craft_process": "选定山场 → 起调（令头）→ 即兴编词（比兴手法）→ 对唱盘歌 → 花儿会竞歌 → 收令。",
        "representative_works": ["《上去高山望平川》", "《白牡丹》", "《水红花令》"],
        "representative_inheritors": ["朱仲禄（“花儿王”）", "张君（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_unesco"],
    },
    {
        "id": "h_shanhuaer",
        "name": "回族山花儿",
        "category": "传统音乐 · 民歌",
        "region": "宁夏回族自治区固原市",
        "era": "元明以来回族民间口传",
        "level": "国家级非物质文化遗产",
        "description": "山花儿是回族群众在山野田间传唱的民歌，曲调高亢悠长、多用假声，歌词以小经文（阿拉伯字母拼写汉语）与汉语混用，题材含劳动、爱情、劝善，与甘肃花儿同源而风格更内敛。",
        "cultural_meaning": "山花儿是回族文化汉回交融的语言标本，记录了西北回族的迁徙、生计与信仰生活。",
        "craft_process": "山野即景起兴 → 假声起调 → 盘歌对答 → 节令歌会集唱。",
        "representative_works": ["《吆骡子》", "《摘花椒》", "《脚户哥》"],
        "representative_inheritors": ["马万章（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_cnfolk"],
    },
    {
        "id": "h_mukamu",
        "name": "新疆维吾尔木卡姆艺术",
        "category": "传统音乐 · 古典音乐",
        "region": "新疆维吾尔自治区喀什地区",
        "era": "源于西域乐舞，16 世纪叶尔羌汗国成体系",
        "level": "国家级非物质文化遗产",
        "description": "维吾尔十二木卡姆是集歌、舞、乐于一体的大型古典音乐套曲，完整演唱需约 24 小时，分穹乃额麦、达斯坦、麦西热甫三部分，含曲令 300 余首。2005 年被联合国教科文组织列入人类口头和非物质遗产代表作名录。",
        "cultural_meaning": "十二木卡姆是丝绸之路上音乐文化交融的结晶，被誉为东方音乐的明珠，维吾尔族以“木卡姆”统称这一音乐体系。",
        "craft_process": "木卡姆选段（穹乃额麦）→ 达斯坦叙事歌 → 麦西热甫集体舞 → 萨塔尔、独他尔、手鼓伴奏 → 现场即兴。",
        "representative_works": ["《十二木卡姆》全套", "《拉克木卡姆》", "《乌夏克木卡姆》"],
        "representative_inheritors": ["吐尔逊·买买提（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_unesco"],
    },
    {
        "id": "h_gspiy",
        "name": "环县道情皮影戏",
        "category": "传统戏剧 · 皮影戏",
        "region": "甘肃省庆阳市环县",
        "era": "宋代皮影戏传入陇东",
        "level": "国家级非物质文化遗产",
        "description": "环县道情皮影以道情（道教音乐遗存）演唱，一人操控五根签子完成走跑跳打，乐队以四胡、水梆、干鼓伴奏。剧目以神戏、马戏见长，唱腔分慢板、飞板，声腔苍凉遒劲。",
        "cultural_meaning": "道情皮影是陇东农耕社会的露天剧场，兼具酬神、教化与娱乐功能，其道情唱腔是研究道教音乐世俗化的标本。",
        "craft_process": "选牛皮刮制 → 描样镂刻（推皮走刀）→ 敷彩点染 → 缀结装订 → 签子调试 → 搭台亮子演唱。",
        "representative_works": ["《封神演义》系列", "《王琪买老》", "道情《八仙庆寿》"],
        "representative_inheritors": ["史成林（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_cnfolk"],
    },
    {
        "id": "h_hkqingjiao",
        "name": "长洲太平清醮",
        "category": "民俗 · 民间信俗",
        "region": "香港特别行政区长洲",
        "era": "清代同治年间传承至今",
        "level": "国家级非物质文化遗产",
        "description": "长洲太平清醮是香港长洲岛每年农历四月举行的酬神祈安仪式，以“抢包山”与飘色巡游闻名。醮期内全岛素斋，居民扎制平安包山，巡游中儿童扮成古今人物立于高杆，入夜后众人攀爬包山争夺平安包。2011 年列入第三批国家级非物质文化遗产代表性项目名录。",
        "cultural_meaning": "太平清醮承载岭南酬神禳灾的信俗传统，也是香港渔村社区凝聚力的年度盛典，体现中华节俗在都市海岛的活态延续。",
        "craft_process": "建醮（立醮坛、请神）→ 斋戒素食 → 扎作包山与飘色 → 神明巡游 → 抢包山 → 送神回銮。",
        "representative_works": ["抢包山", "飘色巡游", "平安包（包山馒头）"],
        "representative_inheritors": ["长洲居民协会（团体传承）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
    {
        "id": "h_motauju",
        "name": "土生土语话剧",
        "category": "传统戏剧 · 话剧",
        "region": "澳门特别行政区",
        "era": "20 世纪中叶在澳门成型",
        "level": "国家级非物质文化遗产",
        "description": "土生土语话剧使用澳门土生葡人语言（以葡萄牙语为骨架、吸收粤语与马来语等词汇的克里奥尔语）演绎舞台喜剧，借语调、语码转换与文化差异制造幽默，维系土生葡人的在地情感。2021 年列入第五批国家级非物质文化遗产代表性项目名录。",
        "cultural_meaning": "土生土语话剧是中西文化在澳门四百余年交融的语言结晶，也是澳门作为多元文化共存城市的独特文化标识。",
        "craft_process": "土生土语创作剧本 → 排练（口语与双关设计）→ 剧场演出 → 社区巡演与传习培养。",
        "representative_works": ["《美丽人生》", "《婆婆也疯狂》", "《再见澳门》"],
        "representative_inheritors": ["飞文基（国家级代表性传承人）"],
        "source_ids": ["src_ihchina", "src_zhwiki"],
    },
]


def main() -> None:
    items = json.loads(DATA.read_text(encoding="utf-8"))
    if isinstance(items, dict):
        items = items["items"]
    have = {i["id"] for i in items}
    added = []
    for it in NEW:
        if it["id"] in have:
            continue
        items.append(it)
        added.append(it["id"])
    DATA.write_text(json.dumps(items, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"total={len(items)} added={len(added)} {added}")


if __name__ == "__main__":
    main()
